apiVersion: v1
kind: Service
metadata:
  name: godemo
spec:
  selector:
    app: godemo
    env: production
    color: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
