apiVersion:	extensions/v1beta1
kind: Deployment
metadata:
  name: godemo-blue
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: godemo
        env: production
        color: blue
    spec:
      containers:
      - name: godemo
        image: containers.lab.cloud104.io/godemo:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      terminationGracePeriodSeconds: 5